name: veracrypt
on:
  push:
    paths-ignore:
      - 'Tests/**'
      - 'doc/**'
      - '*.md'
    branches:
    - master
  pull_request:
    branches:
    - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  ubuntu-20:
    name: 🐧 test Ubuntu-20    
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - uses: kenchan0130/actions-system-info@master
        id: sysinfo
      - name: Install compiler and dependencies
        run: |
          sudo apt-get install -q -y --no-install-recommends make pkg-config g++ yasm ccache wget libfuse-dev libgtk-3-dev
      - uses: actions/checkout@v3
      - name: Cache wxWidgets build
        id: cache-wx
        uses: actions/cache@v3
        env:
          cache-name: cache-wxwidgets
        with:
          path: wxWidgets
          key: ${{ steps.sysinfo.outputs.release }}-build-${{ env.cache-name }}-${{ hashFiles('wxWidgets/**') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - if: ${{ steps.cache-wx.outputs.cache-hit != 'true' }}
        name: Download wxWidgets 3.2.1
        run: |
          wget -q https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.1/wxWidgets-3.2.1.tar.bz2
          tar xf wxWidgets-3.2.1.tar.bz2
          mv wxWidgets-3.2.1 wxWidgets
      - if: ${{ steps.cache-wx.outputs.cache-hit != 'true' }}
        name: Build wxWidgets
        working-directory: ./src
        run: |
          make WXSTATIC=1 WX_ROOT=`realpath ../wxWidgets` wxbuild
      - name: Build Veracrypt
        working-directory: ./src
        run: |
          make NOGUI=1 WXSTATIC=1
      - uses: actions/upload-artifact@v3
        with:
          name: veracrypt-ubuntu20-amd64
          path: src/Main/veracrypt
